### ISSUE TITLE
Couldn't connect to the api when trying to sign in

### ISSUE THREAD

**Issue by kennedy-dan** [kerberos-io/factory#14]
i am getting an error "Couldn't connect to the API" when trying to sign in for the first time

**Comment by dtrapeznikov** [comment]
Had to deal with this problem and found that thread. For those who're still struggling with it - try changing the MODGODB_HOST variable in mongodb.config.yaml configmap to mongodb.mongodb.svc.cluster.local

**Comment by dtrapeznikov** [comment]
Quick note: better add the environment variable to the kerberos factory deployment.yaml
`        - name: MONGODB_HOST
          value: mongodb.mongodb.svc.cluster.local`
It's important, because it seems that the kerberos agents created by this factory use the variable from the configmap mentioned above. They apparently add the `svc.cluster.local` part by themselves, so if you add the full url to the configmap - the agents won't be able to access the mongodb and will crash
